apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: default
data:
  MILVUS_URL: "host.docker.internal:19530"
  SIMILARITY_SERVICE_URL: "similarity-service.default.svc.cluster.local:80"
