apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-service-config
  namespace: default
data:
  MILVUS_URL: "host.docker.internal:19530"
  SIMILARITY_SERVICE_URL: "similarity-service.default.svc.cluster.local:80"
  ANALYSER_SERVICE_URL: "analyser-service.default.svc.cluster.local:80"
  REDIS_URL: "host.docker.internal:6379"
