apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-service-config
  namespace: default
data:
  MILVUS_URL: "milvus-demo.milvus.svc.cluster.local:19530"
  SIMILARITY_SERVICE_URL: "similarity-service.default.svc.cluster.local:80"
  REDIS_URL: "clustercfg.similarity-app-image-cache.wutpwp.use2.cache.amazonaws.com:6379"
